# GitHub Actions runners: https://github.com/actions/runner-images

name: Build and test

on:
  pull_request:
    paths:
      - Vienna*/**
      - External/**
      - Scripts/**
      - Makefile
      - .github/workflows/*

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-14
            xcode: Xcode 15
            developer-dir: /Applications/Xcode_15.4.app/Contents/Developer
          - os: macos-15
            xcode: Xcode 16
            developer-dir: /Applications/Xcode_16.2.app/Contents/Developer
    name: Test with ${{ matrix.xcode }}
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: ${{ matrix.developer-dir }}
    timeout-minutes: 15

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Vienna
      run: |
        xcodebuild -version
        xcodebuild build-for-testing -project Vienna.xcodeproj -scheme Vienna -configuration Development | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run unit tests
      run: |
        xcodebuild -version
        xcodebuild test -project Vienna.xcodeproj -scheme Vienna -configuration Development | xcpretty && exit ${PIPESTATUS[0]}
